// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTzgLKwX-wvg0S6Q-sQbRaMoMEENevU-Q',
    appId: '1:1070669915777:web:9d749d18b071d096aa4f80',
    messagingSenderId: '1070669915777',
    projectId: 'arm-test-task',
    authDomain: 'arm-test-task.firebaseapp.com',
    storageBucket: 'arm-test-task.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVVxo5xoSf7RyJ6uSs9DCQDDJn94zL1ZI',
    appId: '1:1070669915777:android:a7b0f5b3b08a089faa4f80',
    messagingSenderId: '1070669915777',
    projectId: 'arm-test-task',
    storageBucket: 'arm-test-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0i7XzeLNpJqGqSI1bhexdwkmYXbTT-pk',
    appId: '1:1070669915777:ios:123d43672ac27b74aa4f80',
    messagingSenderId: '1070669915777',
    projectId: 'arm-test-task',
    storageBucket: 'arm-test-task.appspot.com',
    iosBundleId: 'com.example.armTest',
  );
}
